### ISSUE TITLE
The L^2-projrction of Stokes problem

### ISSUE THREAD

**Issue by Yanwei-LI-sd** [Terenceyuyue/mVEM#4]
Hi, Yu!

Sorry to bother you again. I can't continue with the previous comment. So I have to create a new issue. I have read the mixed VEM for Stokes problem. It's very good and it helped me a lot! 

Now I have a question to consult you. I want to know how to calculate L^2-projection when k is greater than 2. I am currently working on the control problem of Stokes equations. In my paper, I need to calculate the \Pi^0_2 projrction. The equation is attached to the picture at the end. My question is to calculate the \Pi^0_2 projrction in the right term.

Can you consider this question when you have time? If possible, can you write the code for the \Pi^0_2 projrction. I am a beginner, there are some problems can not deal with. Please forgive me if I've disturbed you. Looking forward to your reply. Thank you very much!

Yanwei Li, 2021/08/26
![eaution](https://user-images.githubusercontent.com/84770266/130898970-645f1433-bf97-4d6e-95e2-4b361c5f3be0.png)

**Comment by Terenceyuyue** [comment]
\Pi_2^0   (k=2) is not computable.  
We can only compute \Pi_{k-2}^0 , which gives the optimal convergence. 

To compute higher order projections, you need to implement the enhancement technique.  
That is, we first enlarge the VE space to have enough d.o.f.s and then replace the reduant d.o.f.s by the ones of elliptic projection. You should verify that the computing of the elliptic projection doesn't involve the reduant d.o.f.s.

The orginal VE space is denoted by Vk, and the enhanced space is Wk. Please refer to the pioneer work: Equivalent Projectors for Virtual Element Methods

**Comment by Terenceyuyue** [comment]
redundant

**Comment by Terenceyuyue** [comment]
You should notice the exact meaning of the computability.   In the final step, we need to solve the linear system Ax = b, where x is the d.o.f vector. The computability means to form this system w.r.t. x.  

For a known function u, the elliptic projection and L2 projection can be exactly computed. But in this case, the u is unknown.  Note that  x = x(u).

**Comment by Yanwei-LI-sd** [comment]
Thanks for your advice.

I've read this article before. But I don't know how to apply to the Stokes problem and how to construct the enhanced space Wk.

In my opinion, I think calculating \Pi_2^0 has two methods. On the one hand we can calculate \Pi_{k-2}^0, which let k=4. I have tried, but it's very trouble and I can't achieve it. On the other hand, construct the enhanced space Wk to calculate \Pi_k^0. But I don't know how to construct Wk. Are these two methods correct? If correct, I will try it again.

You have uploaded the enhanced space code for the Darcy problem. Will you still upload the enhanced space code for the Stokes problem?
