### ISSUE TITLE
VEM Stokes

### ISSUE THREAD

**Issue by MathPoincare** [Terenceyuyue/mVEM#7]
Dear teacher. I am sam, a graduate student, and I am currently working on the project of virtual element related to Stokes problem. I am very glad to see the code about virtual element written by you on GitHub.I have been keeping an eye on your code update. Will you write VEM code about Stokes problem in the future? It's my pleasure that you update the code about stokes problem.

**Comment by Terenceyuyue** [comment]
The code for Stokes problem is available now.   mVEM needs further improvements and extensions. 
The project has been put on hold for a long time since I haven't engaged in this reaseach in the past year.
